Repository readme update
lee-fcsh/ichigo pull request #5
Opened 2022-06-02 15:25 UTC by maalloor

Created Ichigo Repository Readme!

2022-06-02 20:12 UTC, alealcor requested changes
Se requieren cambios en README.md

2022-06-03 05:14 UTC, maalloor commented
@alealcor . Ya agregué el commit con las correcciones del README.md, pero creo que hice mal en enviar otro commit a la misma rama. No me acuerdo bien como se hacía para el caso que haya la necesidad de corregir. Disculpa la hora.

2022-06-03 13:45 UTC, alealcor commented on README.md
> +- Para ejecutar el experimento a través de la consola, ingresar el comando ```otree devserver```
era así:
```
otree devserver
```

Pero igual también es valido, si deseas le corriges (Te lo recomiendo para que revises), y si no pues dale al merge! 🚀

2022-06-03 13:45 UTC, alealcor approved these changes
LGTM!

2022-06-03 13:47 UTC, alealcor commented
> @alealcor . Ya agregué el commit con las correcciones del README.md, pero creo que hice mal en enviar otro commit a la misma rama. No me acuerdo bien como se hacía para el caso que haya la necesidad de corregir. Disculpa la hora.

No no, esta muy bien, cuando mando a hacer cambios tiene que subirlos a la misma rama y pedir que te vuelvan a revisar, buen trabajo!

2022-06-03 18:34 UTC, merged