Pylint ichigo
lee-fcsh/ichigo pull request #9
Opened 2022-06-09 01:41 UTC by maalloor

Pylint implementation in the Ichigo repository. Please notify any correction to be made.

2022-06-09 18:23 UTC, alealcor requested changes
Las recomendaciones mencionadas por favor en todas las funciones y descripciones

2022-06-09 18:23 UTC, alealcor commented on my_public_goods/__init__.py
> +"""Module otree"""
Mejor descripción del archivo, que contiene o que hace o de que se trata

2022-06-09 18:23 UTC, alealcor commented on my_public_goods/__init__.py
> +DOC = """
Una mejor descripción de lo que trata la app.

2022-06-09 18:23 UTC, alealcor commented on my_survey/__init__.py
> +"""Module otree"""
Same here

2022-06-09 18:23 UTC, alealcor commented on my_trust/__init__.py
> +DOC = """
Aki iwal

2022-06-09 18:23 UTC, alealcor commented on my_trust/__init__.py
> +        """Function that shows the player that he is going to skip the page"""
Mejor descripción de las funciones.

2022-06-09 18:23 UTC, alealcor commented on my_trust/__init__.py
>      def vars_for_template(player):
aaaaaaaaaaaaqui tamben

2022-06-10 15:55 UTC, alealcor approved these changes
Good job! No veo el pylint como los Checks pero de ley te salta hagas merge to main. En caso de que te salga error, corrije y manda nueva PR para que ahi si pueda comprobar los actions.

2022-06-10 15:57 UTC, alealcor commented
@maalloor Recuerda marcar como **Resolve conversaton** cuando termines de corregir lo solicitado.

2022-06-14 14:24 UTC, merged

2022-06-14 14:31 UTC, maalloor commented
Pull request resolve